FORWARD = 1
FORWARD_FAST = 2
BACKWARD = 3
TURN_LEFT = 4
TURN_LEFT_MICRO = 5
TURN_RIGHT = 6
TURN_RIGHT_MICRO = 7
GRAB = 10
RELEASE = 11
BACKWARD_LEFT = 12
BACKWARD_RIGHT = 13
RIGHT_AND_FORWARD = 14
LEFT_AND_FORWARD = 15
LEFT_180_AND_FORWARD = 16
RIGHT_180_AND_FORWARD = 17

# OBJECTS_FROM_START_DEGREE = 245.0
OBJECTS_FROM_START_DEGREE = 247.0

OBJECTS_FROM_RED_AREA_DEGREE = 235.0
OBJECTS_FROM_YELLOW_AREA_DEGREE = OBJECTS_FROM_RED_AREA_DEGREE

OBJECTS_FROM_GREEN_AREA_DEGREE = 267.0
OBJECTS_FROM_BLUE_AREA_DEGREE = OBJECTS_FROM_GREEN_AREA_DEGREE

AREA_BLUE_FROM_OBJECTS_DEGREE = 335.0
AREA_GREEN_FROM_OBJECTS_DEGREE = AREA_BLUE_FROM_OBJECTS_DEGREE

AREA_RED_FROM_OBJECTS_DEGREE = 308.0
AREA_YELLOW_FROM_OBJECTS_DEGREE = AREA_RED_FROM_OBJECTS_DEGREE
